### ISSUE TITLE
conseguir los iconos en svg para los simobolos monetarios

### ISSUE THREAD

**Issue by aledaas** [aledaas/Sass#1]

**Comment by Titus-siano** [comment]
Aca estan los iconos en png de los tipo de monedas. tambien un enlace de la web por si quieren otros diseños de los mismos\

enlace: https://www.flaticon.es

simbolos:
![simbolo-del-yen](https://user-images.githubusercontent.com/81445406/160729273-367320b9-fa24-4eba-8404-652ea200f3a0.png)
![dollar-currency-symbol](https://user-images.githubusercontent.com/81445406/160729277-3efa87c8-dafe-4226-90ef-65cb1b81d833.png)
![euro](https://user-images.githubusercontent.com/81445406/160729279-0967bead-bbe6-403f-bbcc-f31edbaf1d0a.png)
![signo-de-libra-esterlina-de-dinero](https://user-images.githubusercontent.com/81445406/160729281-57711e08-14ec-49f0-861e-efb3278e9a6e.png)
/
